package io.github.skystrike.shared.weapons;

// GENERATED by tools/weapons/generate_weapon_tables.py from assets/sprites/melee.json.
// Edit the catalog or the generator, then re-run it; do not hand-edit the table.

/**
 * Every melee weapon in the game — the sprite-backed rows of the
 * {@code assets/sprites/melee.json} catalog (mechanics §5.2).
 *
 * <p>Melee has slot 3 to itself and can never be removed, so a player is never defenceless.
 * Only identity, the display name and the sprite asset id live here; the numbers are in
 * {@link MeleeRegistry}.
 *
 * <p><b>On the wire</b> a melee weapon is encoded as {@link #WIRE_ID_BASE} plus the ordinal, so
 * the single {@code weaponId} int carried by players, damage events and kill events can name
 * either family: values below the base are {@link WeaponId} ordinals, values at or above it are
 * melee. The encoding is part of the protocol and therefore append-only in exactly the way
 * {@code NetworkRegistration} is.
 */
public enum MeleeId {

    POCKET_THORN("Pocket Thorn", "pocket-thorn"),
    KITCHEN_HOOK("Kitchen Hook", "kitchen-hook"),
    HARBOR_FOLDER("Harbor Folder", "harbor-folder"),
    COPPER_PARING("Copper Paring", "copper-paring"),
    NIGHT_LETTER("Night Letter", "night-letter"),
    ASH_MACHETE("Ash Machete", "ash-machete"),
    TIDE_KUKRI("Tide Kukri", "tide-kukri"),
    TRENCH_KNUCKLE("Trench Knuckle", "trench-knuckle"),
    SALT_BOLO("Salt Bolo", "salt-bolo"),
    WINTER_KATANA("Winter Katana", "winter-katana"),
    BLACK_NODACHI("Black Nodachi", "black-nodachi"),
    MILL_ZWEI("Mill Zwei", "mill-zwei"),
    ASH_FALCHION("Ash Falchion", "ash-falchion"),
    HARBOR_HANGER("Harbor Hanger", "harbor-hanger"),
    FROST_NAGINATA("Frost Naginata", "frost-naginata"),
    YARD_WRENCH("Yard Wrench", "yard-wrench"),
    QUIET_PROD("Quiet Prod", "quiet-prod"),
    EMBER_CHAINSAW("Ember Chainsaw", "ember-chainsaw"),
    OAK_BO("Oak Bo", "oak-bo"),
    WINTER_TANTO("Winter Tanto", "winter-tanto"),
    BLACK_WAKIZASHI("Black Wakizashi", "black-wakizashi");

    /** Wire encoding offset: {@code wireId = WIRE_ID_BASE + ordinal}. Never reuse or renumber. */
    public static final int WIRE_ID_BASE = 1000;

    /** The melee weapon a player carries before any loadout choice exists. */
    public static final MeleeId DEFAULT = TRENCH_KNUCKLE;

    private final String displayName;
    private final String assetId;

    MeleeId(String displayName, String assetId) {
        this.displayName = displayName;
        this.assetId = assetId;
    }

    public String displayName() {
        return displayName;
    }

    /** The catalog id, which is also the sprite file name under {@code sprites/melee/}. */
    public String assetId() {
        return assetId;
    }

    /** The value this weapon takes in a {@code weaponId} field on the wire. */
    public int wireId() {
        return WIRE_ID_BASE + ordinal();
    }

    /** True when {@code wireId} encodes a melee weapon rather than a gun. */
    public static boolean isMeleeWireId(int wireId) {
        return wireId >= WIRE_ID_BASE && wireId < WIRE_ID_BASE + values().length;
    }

    /** Inverse of {@link #wireId()}. Out-of-range values fall back to {@link #DEFAULT}. */
    public static MeleeId fromWireId(int wireId) {
        return fromOrdinal(wireId - WIRE_ID_BASE);
    }

    /** Lookup by ordinal. Out-of-range values fall back to {@link #DEFAULT}. */
    public static MeleeId fromOrdinal(int ordinal) {
        MeleeId[] ids = values();
        if (ordinal < 0 || ordinal >= ids.length) {
            return DEFAULT;
        }
        return ids[ordinal];
    }

    /** True when {@code ordinal} names a real melee weapon. */
    public static boolean isValidOrdinal(int ordinal) {
        return ordinal >= 0 && ordinal < values().length;
    }
}
