package io.github.skystrike.shared.weapons;

// GENERATED by tools/weapons/generate_weapon_tables.py from assets/sprites/guns.json.
// Edit the catalog or the generator, then re-run it; do not hand-edit the table.

import io.github.skystrike.shared.config.CombatConfig;
import java.util.EnumMap;
import java.util.Map;

/**
 * Per-weapon flight behaviour: muzzle speed, drop, drag and damage falloff (mechanics §4.2).
 *
 * <p>Shared on purpose. The server resolves hits with these numbers, and the client draws
 * tracers and (from Phase 7) a predicted point of impact with them; a second copy of the table
 * would quietly put the two pictures out of step.
 *
 * @param weaponClass    family, which fixes the relative drop weight
 * @param muzzleSpeed    units per second at the muzzle; sidearms have a dedicated 1200 floor
 * @param dragPerTick    speed retained per 60 Hz tick, 0.980 (shotguns) to 0.998 (snipers)
 * @param gravityRampSeconds time over which drop ramps in, so rounds fly flat up close
 * @param maxRange       distance at which damage reaches its floor, from the weapon table
 * @param minDamageRatio damage retained at maximum range, 0.35 (shotguns) to 0.80 (snipers)
 */
public record WeaponBallistics(
    WeaponClass weaponClass,
    float muzzleSpeed,
    float dragPerTick,
    float gravityRampSeconds,
    float maxRange,
    float minDamageRatio
) {

    public WeaponBallistics {
        if (muzzleSpeed <= 0f) {
            throw new IllegalArgumentException("muzzle speed must be positive: " + muzzleSpeed);
        }
        if (dragPerTick <= 0f || dragPerTick > 1f) {
            throw new IllegalArgumentException("drag must be in (0, 1]: " + dragPerTick);
        }
        if (gravityRampSeconds <= 0f) {
            throw new IllegalArgumentException("gravity ramp must be positive: " + gravityRampSeconds);
        }
        if (maxRange <= 0f) {
            throw new IllegalArgumentException("max range must be positive: " + maxRange);
        }
        if (minDamageRatio <= 0f || minDamageRatio > 1f) {
            throw new IllegalArgumentException("damage floor must be in (0, 1]: " + minDamageRatio);
        }
    }

    /** Downward acceleration weight for this weapon's family (sniper 1.0 → shotgun 5.0). */
    public float gravityWeight() {
        return weaponClass.gravityWeight();
    }

    /** Fully ramped-in drop acceleration in units/s², always negative. */
    public float terminalGravity() {
        return -CombatConfig.BULLET_GRAVITY_BASE * gravityWeight();
    }

    private static final Map<WeaponId, WeaponBallistics> TABLE = buildTable();

    /** The flight profile of one weapon. Never null. */
    public static WeaponBallistics of(WeaponId id) {
        WeaponBallistics ballistics = TABLE.get(id);
        if (ballistics == null) {
            throw new IllegalArgumentException("no ballistics for weapon: " + id);
        }
        return ballistics;
    }

    /** The whole table, for validation and tooling. */
    public static Map<WeaponId, WeaponBallistics> all() {
        return TABLE;
    }

    private static Map<WeaponId, WeaponBallistics> buildTable() {
        Map<WeaponId, WeaponBallistics> table = new EnumMap<>(WeaponId.class);
        table.put(WeaponId.IRON_SIDEARM,
            new WeaponBallistics(WeaponClass.PISTOL, 1340f, 0.995f, 1f, 392f, 0.55f));
        table.put(WeaponId.VESPER_9,
            new WeaponBallistics(WeaponClass.PISTOL, 1332f, 0.995f, 1f, 420f, 0.55f));
        table.put(WeaponId.NEST_HAWK,
            new WeaponBallistics(WeaponClass.PISTOL, 1310f, 0.995f, 1f, 308f, 0.55f));
        table.put(WeaponId.COBALT_COMPACT,
            new WeaponBallistics(WeaponClass.PISTOL, 1235f, 0.995f, 1f, 252f, 0.55f));
        table.put(WeaponId.ASHEN_SERVICE,
            new WeaponBallistics(WeaponClass.PISTOL, 1362f, 0.995f, 1f, 448f, 0.55f));
        table.put(WeaponId.REDLINE_45,
            new WeaponBallistics(WeaponClass.PISTOL, 1200f, 0.995f, 1f, 364f, 0.55f));
        table.put(WeaponId.GLASS_NEEDLER,
            new WeaponBallistics(WeaponClass.PISTOL, 1415f, 0.995f, 1f, 532f, 0.55f));
        table.put(WeaponId.HARBOR_19,
            new WeaponBallistics(WeaponClass.PISTOL, 1325f, 0.995f, 1f, 378f, 0.55f));
        table.put(WeaponId.NIGHT_CLERK,
            new WeaponBallistics(WeaponClass.PISTOL, 1265f, 0.995f, 1f, 336f, 0.55f));
        table.put(WeaponId.RUST_MARSHAL,
            new WeaponBallistics(WeaponClass.PISTOL, 1200f, 0.995f, 1f, 350f, 0.55f));
        table.put(WeaponId.TWIN_PEAK,
            new WeaponBallistics(WeaponClass.PISTOL, 1385f, 0.995f, 1f, 434f, 0.55f));
        table.put(WeaponId.QUIET_LEDGER,
            new WeaponBallistics(WeaponClass.PISTOL, 1280f, 0.995f, 1f, 364f, 0.55f));
        table.put(WeaponId.BRASS_JUDGE,
            new WeaponBallistics(WeaponClass.REVOLVER, 1220f, 0.995f, 1f, 196f, 0.55f));
        table.put(WeaponId.EMBER_WHEEL,
            new WeaponBallistics(WeaponClass.REVOLVER, 1460f, 0.995f, 1f, 504f, 0.55f));
        table.put(WeaponId.DUST_CYLINDER,
            new WeaponBallistics(WeaponClass.REVOLVER, 1250f, 0.995f, 1f, 392f, 0.55f));
        table.put(WeaponId.LONGSPUR_44,
            new WeaponBallistics(WeaponClass.REVOLVER, 1490f, 0.995f, 1f, 560f, 0.55f));
        table.put(WeaponId.GRAVE_ORBIT,
            new WeaponBallistics(WeaponClass.REVOLVER, 1385f, 0.995f, 1f, 308f, 0.55f));
        table.put(WeaponId.COPPER_LAW,
            new WeaponBallistics(WeaponClass.REVOLVER, 1310f, 0.995f, 1f, 364f, 0.55f));
        table.put(WeaponId.BREAKDAWN,
            new WeaponBallistics(WeaponClass.REVOLVER, 1415f, 0.995f, 1f, 420f, 0.55f));
        table.put(WeaponId.IRON_SIX,
            new WeaponBallistics(WeaponClass.REVOLVER, 1430f, 0.995f, 1f, 448f, 0.55f));
        table.put(WeaponId.WASP_NEST,
            new WeaponBallistics(WeaponClass.SMG, 760f, 0.9803f, 0.8f, 392f, 0.42f));
        table.put(WeaponId.RATTLE_CAGE,
            new WeaponBallistics(WeaponClass.SMG, 700f, 0.98f, 0.8f, 308f, 0.42f));
        table.put(WeaponId.SMOKE_STITCH,
            new WeaponBallistics(WeaponClass.PDW, 1430f, 0.9914f, 0.8f, 476f, 0.45f));
        table.put(WeaponId.METRO_SPRAY,
            new WeaponBallistics(WeaponClass.SMG, 560f, 0.98f, 0.8f, 224f, 0.42f));
        table.put(WeaponId.VELVET_BUZZ,
            new WeaponBallistics(WeaponClass.SMG, 680f, 0.98f, 0.8f, 336f, 0.42f));
        table.put(WeaponId.GRID_HORNET,
            new WeaponBallistics(WeaponClass.PDW, 1360f, 0.9902f, 0.8f, 420f, 0.45f));
        table.put(WeaponId.CINDER_SMG,
            new WeaponBallistics(WeaponClass.SMG, 940f, 0.9833f, 0.8f, 364f, 0.42f));
        table.put(WeaponId.POCKET_STORM,
            new WeaponBallistics(WeaponClass.SMG, 720f, 0.98f, 0.8f, 280f, 0.42f));
        table.put(WeaponId.WIRE_CHOIR,
            new WeaponBallistics(WeaponClass.SMG, 730f, 0.98f, 0.8f, 336f, 0.42f));
        table.put(WeaponId.ASH_HOPPER,
            new WeaponBallistics(WeaponClass.SMG, 560f, 0.98f, 0.8f, 364f, 0.42f));
        table.put(WeaponId.CLIP_DAISY,
            new WeaponBallistics(WeaponClass.SMG, 540f, 0.98f, 0.8f, 280f, 0.42f));
        table.put(WeaponId.NEON_CHATTER,
            new WeaponBallistics(WeaponClass.SMG, 780f, 0.9807f, 0.8f, 308f, 0.42f));
        table.put(WeaponId.HARBOR_SWARM,
            new WeaponBallistics(WeaponClass.SMG, 740f, 0.98f, 0.8f, 350f, 0.42f));
        table.put(WeaponId.SOFT_RATCHET,
            new WeaponBallistics(WeaponClass.SMG, 600f, 0.98f, 0.8f, 322f, 0.42f));
        table.put(WeaponId.COAT_NEEDLE,
            new WeaponBallistics(WeaponClass.PDW, 680f, 0.98f, 0.8f, 252f, 0.45f));
        table.put(WeaponId.BRIEFCASE,
            new WeaponBallistics(WeaponClass.PDW, 660f, 0.98f, 0.8f, 280f, 0.45f));
        table.put(WeaponId.IRON_CARBINE,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1640f, 0.9949f, 1.2f, 770f, 0.7f));
        table.put(WeaponId.RIDGEBACK,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1430f, 0.9914f, 1.2f, 700f, 0.7f));
        table.put(WeaponId.PALE_LANCE,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1700f, 0.9958f, 1.2f, 840f, 0.7f));
        table.put(WeaponId.SAND_VIPER,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1600f, 0.9942f, 1.2f, 728f, 0.7f));
        table.put(WeaponId.BLACK_CORRIDOR,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1480f, 0.9922f, 1.2f, 588f, 0.7f));
        table.put(WeaponId.OAKLINE_RIFLE,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1760f, 0.9968f, 1.2f, 896f, 0.7f));
        table.put(WeaponId.HALCYON_16,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1580f, 0.9939f, 1.2f, 672f, 0.7f));
        table.put(WeaponId.BRINE_CARBINE,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1620f, 0.9945f, 1.2f, 756f, 0.7f));
        table.put(WeaponId.SOLAR_SPINE,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1680f, 0.9955f, 1.2f, 812f, 0.7f));
        table.put(WeaponId.FROST_RECEIVER,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1720f, 0.9962f, 1.2f, 868f, 0.7f));
        table.put(WeaponId.EMBER_PATH,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1760f, 0.9968f, 1.2f, 700f, 0.7f));
        table.put(WeaponId.KESTREL_AR,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1460f, 0.9919f, 1.2f, 560f, 0.7f));
        table.put(WeaponId.DUSK_FOLD,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1380f, 0.9906f, 1.2f, 644f, 0.7f));
        table.put(WeaponId.COPPER_THREAD,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1660f, 0.9952f, 1.2f, 784f, 0.7f));
        table.put(WeaponId.YARD_DOG,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1520f, 0.9929f, 1.2f, 616f, 0.7f));
        table.put(WeaponId.QUIET_HOLLOW,
            new WeaponBallistics(WeaponClass.ASSAULT_RIFLE, 1240f, 0.9882f, 1.2f, 532f, 0.7f));
        table.put(WeaponId.VEST_STING,
            new WeaponBallistics(WeaponClass.PDW, 700f, 0.98f, 0.8f, 266f, 0.45f));
        table.put(WeaponId.METRO_FOLD,
            new WeaponBallistics(WeaponClass.PDW, 710f, 0.98f, 0.8f, 294f, 0.45f));
        table.put(WeaponId.LONG_MILE,
            new WeaponBallistics(WeaponClass.DMR, 1680f, 0.9955f, 1.5f, 1176f, 0.72f));
        table.put(WeaponId.GLASS_RIDGE,
            new WeaponBallistics(WeaponClass.DMR, 1760f, 0.9968f, 1.5f, 1204f, 0.72f));
        table.put(WeaponId.THORN_DMR,
            new WeaponBallistics(WeaponClass.DMR, 1700f, 0.9958f, 1.5f, 1148f, 0.72f));
        table.put(WeaponId.HARBOR_MARKSMAN,
            new WeaponBallistics(WeaponClass.DMR, 1640f, 0.9949f, 1.5f, 1120f, 0.72f));
        table.put(WeaponId.IRON_LEDGER,
            new WeaponBallistics(WeaponClass.BATTLE_RIFLE, 1620f, 0.9945f, 1.3f, 1008f, 0.7f));
        table.put(WeaponId.PALE_WITNESS,
            new WeaponBallistics(WeaponClass.DMR, 1800f, 0.9975f, 1.5f, 1232f, 0.72f));
        table.put(WeaponId.RANGE_CLERK,
            new WeaponBallistics(WeaponClass.DMR, 1780f, 0.9972f, 1.5f, 1036f, 0.72f));
        table.put(WeaponId.ASH_PIN,
            new WeaponBallistics(WeaponClass.DMR, 1660f, 0.9952f, 1.5f, 1162f, 0.72f));
        table.put(WeaponId.COPPER_SPAN,
            new WeaponBallistics(WeaponClass.BATTLE_RIFLE, 1600f, 0.9942f, 1.3f, 980f, 0.7f));
        table.put(WeaponId.HIGH_BENCH,
            new WeaponBallistics(WeaponClass.DMR, 1720f, 0.9962f, 1.5f, 1260f, 0.72f));
        table.put(WeaponId.NIGHT_GLASS,
            new WeaponBallistics(WeaponClass.SNIPER, 1700f, 0.9958f, 1.8f, 1540f, 0.8f));
        table.put(WeaponId.WINTER_BOLT,
            new WeaponBallistics(WeaponClass.SNIPER, 1660f, 0.9952f, 1.8f, 1610f, 0.8f));
        table.put(WeaponId.CATHEDRAL,
            new WeaponBallistics(WeaponClass.SNIPER, 1820f, 0.9978f, 1.8f, 1890f, 0.8f));
        table.put(WeaponId.LONG_SILENCE,
            new WeaponBallistics(WeaponClass.SNIPER, 1560f, 0.9935f, 1.8f, 1400f, 0.8f));
        table.put(WeaponId.MAGPIE,
            new WeaponBallistics(WeaponClass.SNIPER, 1720f, 0.9962f, 1.8f, 2100f, 0.8f));
        table.put(WeaponId.ICE_SPINE,
            new WeaponBallistics(WeaponClass.SNIPER, 1800f, 0.9975f, 1.8f, 1820f, 0.8f));
        table.put(WeaponId.DISTANT_CLERK,
            new WeaponBallistics(WeaponClass.SNIPER, 1600f, 0.9942f, 1.8f, 1330f, 0.8f));
        table.put(WeaponId.BLACK_HORIZON,
            new WeaponBallistics(WeaponClass.SNIPER, 1760f, 0.9968f, 1.8f, 1750f, 0.8f));
        table.put(WeaponId.EMBER_GLASS,
            new WeaponBallistics(WeaponClass.SNIPER, 1740f, 0.9965f, 1.8f, 1680f, 0.8f));
        table.put(WeaponId.TIDE_NEEDLE,
            new WeaponBallistics(WeaponClass.SNIPER, 1680f, 0.9955f, 1.8f, 1575f, 0.8f));
        table.put(WeaponId.DOOR_HYMN,
            new WeaponBallistics(WeaponClass.SHOTGUN, 800f, 0.981f, 0.5f, 196f, 0.35f));
        table.put(WeaponId.ROOM_SWEEPER,
            new WeaponBallistics(WeaponClass.SHOTGUN, 780f, 0.9807f, 0.5f, 168f, 0.35f));
        table.put(WeaponId.IRON_GOOSE,
            new WeaponBallistics(WeaponClass.SHOTGUN, 840f, 0.9817f, 0.5f, 308f, 0.35f));
        table.put(WeaponId.SCATTER_BENCH,
            new WeaponBallistics(WeaponClass.SHOTGUN, 810f, 0.9812f, 0.5f, 224f, 0.35f));
        table.put(WeaponId.PUMP_CHAPEL,
            new WeaponBallistics(WeaponClass.SHOTGUN, 770f, 0.9805f, 0.5f, 140f, 0.35f));
        table.put(WeaponId.MAGPIE_12,
            new WeaponBallistics(WeaponClass.SHOTGUN, 830f, 0.9815f, 0.5f, 280f, 0.35f));
        table.put(WeaponId.HARBOR_GATE,
            new WeaponBallistics(WeaponClass.SHOTGUN, 800f, 0.981f, 0.5f, 210f, 0.35f));
        table.put(WeaponId.CINDER_TUBE,
            new WeaponBallistics(WeaponClass.SHOTGUN, 740f, 0.98f, 0.5f, 126f, 0.35f));
        table.put(WeaponId.SHORT_GOSPEL,
            new WeaponBallistics(WeaponClass.SHOTGUN, 720f, 0.98f, 0.5f, 112f, 0.35f));
        table.put(WeaponId.TWIN_BARREL,
            new WeaponBallistics(WeaponClass.SHOTGUN, 790f, 0.9808f, 0.5f, 224f, 0.35f));
        table.put(WeaponId.ASH_HOPPER_12,
            new WeaponBallistics(WeaponClass.SHOTGUN, 770f, 0.9805f, 0.5f, 182f, 0.35f));
        table.put(WeaponId.MILLSTONE,
            new WeaponBallistics(WeaponClass.LMG, 1640f, 0.9949f, 1.2f, 868f, 0.7f));
        table.put(WeaponId.BELT_HYMN,
            new WeaponBallistics(WeaponClass.LMG, 1600f, 0.9942f, 1.2f, 980f, 0.7f));
        table.put(WeaponId.IRON_RAIN,
            new WeaponBallistics(WeaponClass.LMG, 1620f, 0.9945f, 1.2f, 952f, 0.7f));
        table.put(WeaponId.YARD_SAW,
            new WeaponBallistics(WeaponClass.LMG, 1460f, 0.9919f, 1.2f, 812f, 0.7f));
        return java.util.Collections.unmodifiableMap(table);
    }
}
