package io.github.skystrike.shared.weapons;

// GENERATED by tools/weapons/generate_weapon_tables.py from assets/sprites/guns.json.
// Edit the catalog or the generator, then re-run it; do not hand-edit the table.

/**
 * Every gun in the game, as a stable identity both sides can name — the sprite-backed rows
 * of the {@code assets/sprites/guns.json} catalog (mechanics §5.1).
 *
 * <p>Only identity, the display name and the sprite asset id live here. Ballistics are in
 * {@link WeaponBallistics}; the rest of the weapon table (including the ammunition numbers the
 * loadout needs) is in {@link WeaponRegistry}, keyed off this enum.
 *
 * <p><b>Ordinals cross the wire</b> (the input packet carries a selection index), so this list is
 * append-only in exactly the way {@code NetworkRegistration} is: catalog entries that gain
 * sprites later join at the end, never in catalog order.
 */
public enum WeaponId {

    // --- PISTOL ----------------------------------------------------------------------------------
    IRON_SIDEARM("Iron Sidearm", "iron-sidearm"),
    VESPER_9("Vesper 9", "vesper-9"),
    NEST_HAWK("Nest Hawk", "nest-hawk"),
    COBALT_COMPACT("Cobalt Compact", "cobalt-compact"),
    ASHEN_SERVICE("Ashen Service", "ashen-service"),
    REDLINE_45("Redline .45", "redline-45"),
    GLASS_NEEDLER("Glass Needler", "glass-needler"),
    HARBOR_19("Harbor 19", "harbor-19"),
    NIGHT_CLERK("Night Clerk", "night-clerk"),
    RUST_MARSHAL("Rust Marshal", "rust-marshal"),
    TWIN_PEAK("Twin Peak", "twin-peak"),
    QUIET_LEDGER("Quiet Ledger", "quiet-ledger"),

    // --- REVOLVER --------------------------------------------------------------------------------
    BRASS_JUDGE("Brass Judge", "brass-judge"),
    EMBER_WHEEL("Ember Wheel", "ember-wheel"),
    DUST_CYLINDER("Dust Cylinder", "dust-cylinder"),
    LONGSPUR_44("Longspur .44", "longspur-44"),
    GRAVE_ORBIT("Grave Orbit", "grave-orbit"),
    COPPER_LAW("Copper Law", "copper-law"),
    BREAKDAWN("Breakdawn", "breakdawn"),
    IRON_SIX("Iron Six", "iron-six"),

    // --- SMG -------------------------------------------------------------------------------------
    WASP_NEST("Wasp Nest", "wasp-nest"),
    RATTLE_CAGE("Rattle Cage", "rattle-cage"),

    // --- PDW -------------------------------------------------------------------------------------
    SMOKE_STITCH("Smoke Stitch", "smoke-stitch"),

    // --- SMG -------------------------------------------------------------------------------------
    METRO_SPRAY("Metro Spray", "metro-spray"),
    VELVET_BUZZ("Velvet Buzz", "velvet-buzz"),

    // --- PDW -------------------------------------------------------------------------------------
    GRID_HORNET("Grid Hornet", "grid-hornet"),

    // --- SMG -------------------------------------------------------------------------------------
    CINDER_SMG("Cinder SMG", "cinder-smg"),
    POCKET_STORM("Pocket Storm", "pocket-storm"),
    WIRE_CHOIR("Wire Choir", "wire-choir"),
    ASH_HOPPER("Ash Hopper", "ash-hopper"),
    CLIP_DAISY("Clip Daisy", "clip-daisy"),
    NEON_CHATTER("Neon Chatter", "neon-chatter"),
    HARBOR_SWARM("Harbor Swarm", "harbor-swarm"),
    SOFT_RATCHET("Soft Ratchet", "soft-ratchet"),

    // --- PDW -------------------------------------------------------------------------------------
    COAT_NEEDLE("Coat Needle", "coat-needle"),
    BRIEFCASE("Briefcase", "briefcase"),

    // --- ASSAULT_RIFLE ---------------------------------------------------------------------------
    IRON_CARBINE("Iron Carbine", "iron-carbine"),
    RIDGEBACK("Ridgeback", "ridgeback"),
    PALE_LANCE("Pale Lance", "pale-lance"),
    SAND_VIPER("Sand Viper", "sand-viper"),
    BLACK_CORRIDOR("Black Corridor", "black-corridor"),
    OAKLINE_RIFLE("Oakline Rifle", "oakline-rifle"),
    HALCYON_16("Halcyon 16", "halcyon-16"),
    BRINE_CARBINE("Brine Carbine", "brine-carbine"),
    SOLAR_SPINE("Solar Spine", "solar-spine"),
    FROST_RECEIVER("Frost Receiver", "frost-receiver"),
    EMBER_PATH("Ember Path", "ember-path"),
    KESTREL_AR("Kestrel AR", "kestrel-ar"),
    DUSK_FOLD("Dusk Fold", "dusk-fold"),
    COPPER_THREAD("Copper Thread", "copper-thread"),
    YARD_DOG("Yard Dog", "yard-dog"),
    QUIET_HOLLOW("Quiet Hollow", "quiet-hollow"),

    // --- PDW -------------------------------------------------------------------------------------
    VEST_STING("Vest Sting", "vest-sting"),
    METRO_FOLD("Metro Fold", "metro-fold"),

    // --- DMR -------------------------------------------------------------------------------------
    LONG_MILE("Long Mile", "long-mile"),
    GLASS_RIDGE("Glass Ridge", "glass-ridge"),
    THORN_DMR("Thorn DMR", "thorn-dmr"),
    HARBOR_MARKSMAN("Harbor Marksman", "harbor-marksman"),

    // --- BATTLE_RIFLE ----------------------------------------------------------------------------
    IRON_LEDGER("Iron Ledger", "iron-ledger"),

    // --- DMR -------------------------------------------------------------------------------------
    PALE_WITNESS("Pale Witness", "pale-witness"),
    RANGE_CLERK("Range Clerk", "range-clerk"),
    ASH_PIN("Ash Pin", "ash-pin"),

    // --- BATTLE_RIFLE ----------------------------------------------------------------------------
    COPPER_SPAN("Copper Span", "copper-span"),

    // --- DMR -------------------------------------------------------------------------------------
    HIGH_BENCH("High Bench", "high-bench"),

    // --- SNIPER ----------------------------------------------------------------------------------
    NIGHT_GLASS("Night Glass", "night-glass"),
    WINTER_BOLT("Winter Bolt", "winter-bolt"),
    CATHEDRAL("Cathedral", "cathedral"),
    LONG_SILENCE("Long Silence", "long-silence"),
    MAGPIE("Magpie", "magpie"),
    ICE_SPINE("Ice Spine", "ice-spine"),
    DISTANT_CLERK("Distant Clerk", "distant-clerk"),
    BLACK_HORIZON("Black Horizon", "black-horizon"),
    EMBER_GLASS("Ember Glass", "ember-glass"),
    TIDE_NEEDLE("Tide Needle", "tide-needle"),

    // --- SHOTGUN ---------------------------------------------------------------------------------
    DOOR_HYMN("Door Hymn", "door-hymn"),
    ROOM_SWEEPER("Room Sweeper", "room-sweeper"),
    IRON_GOOSE("Iron Goose", "iron-goose"),
    SCATTER_BENCH("Scatter Bench", "scatter-bench"),
    PUMP_CHAPEL("Pump Chapel", "pump-chapel"),
    MAGPIE_12("Magpie 12", "magpie-12"),
    HARBOR_GATE("Harbor Gate", "harbor-gate"),
    CINDER_TUBE("Cinder Tube", "cinder-tube"),
    SHORT_GOSPEL("Short Gospel", "short-gospel"),
    TWIN_BARREL("Twin Barrel", "twin-barrel"),
    ASH_HOPPER_12("Ash Hopper 12", "ash-hopper-12"),

    // --- LMG -------------------------------------------------------------------------------------
    MILLSTONE("Millstone", "millstone"),
    BELT_HYMN("Belt Hymn", "belt-hymn"),
    IRON_RAIN("Iron Rain", "iron-rain"),
    YARD_SAW("Yard Saw", "yard-saw");

    /** The primary of the default loadout — a player is never defenceless. */
    public static final WeaponId DEFAULT = IRON_CARBINE;

    /** The sidearm of the default loadout. */
    public static final WeaponId DEFAULT_SIDEARM = IRON_SIDEARM;

    private final String displayName;
    private final String assetId;

    WeaponId(String displayName, String assetId) {
        this.displayName = displayName;
        this.assetId = assetId;
    }

    public String displayName() {
        return displayName;
    }

    /** The catalog id, which is also the sprite file name under {@code sprites/guns/}. */
    public String assetId() {
        return assetId;
    }

    /** Lookup by wire ordinal. Out-of-range values fall back to {@link #DEFAULT}. */
    public static WeaponId fromOrdinal(int ordinal) {
        WeaponId[] ids = values();
        if (ordinal < 0 || ordinal >= ids.length) {
            return DEFAULT;
        }
        return ids[ordinal];
    }

    /** True when {@code ordinal} names a real weapon. */
    public static boolean isValidOrdinal(int ordinal) {
        return ordinal >= 0 && ordinal < values().length;
    }
}
