package io.github.skystrike.shared.weapons;

// GENERATED by tools/weapons/generate_weapon_tables.py from assets/sprites/guns.json.
// Edit the catalog or the generator, then re-run it; do not hand-edit the table.

import java.util.Collections;
import java.util.EnumMap;
import java.util.Map;

/**
 * The gun table: id → definition, for every sprite-backed gun of the catalog (mechanics §5.1).
 *
 * <p>Lookups <b>return copies</b>. A shared mutable definition handed to every player would be a
 * cross-player state leak — one player editing their weapon would edit everyone's. The
 * definitions are immutable records today, so the copy is cheap insurance, but the contract is
 * the point: callers may do what they like with what they get.
 *
 * <p>This registry is the single source of truth for per-weapon parameters. The rows are
 * generated from {@code assets/sprites/guns.json} by the documented unit conversions in
 * {@code tools/weapons/generate_weapon_tables.py}; live state — spread, cooldown, ammunition —
 * stays server-authoritative and never lives here.
 */
public final class WeaponRegistry {

    private WeaponRegistry() {
    }

    /** Fire parameters for one weapon, as a fresh copy. Never null. */
    public static WeaponDefinition of(WeaponId id) {
        WeaponDefinition definition = TABLE.get(id);
        if (definition == null) {
            throw new IllegalArgumentException("no definition for weapon: " + id);
        }
        return definition.copy();
    }

    /** Fire parameters by wire ordinal, falling back to the default weapon. */
    public static WeaponDefinition ofOrdinal(int ordinal) {
        return of(WeaponId.fromOrdinal(ordinal));
    }

    /** The whole table, for validation and tooling. Values are copies. */
    public static Map<WeaponId, WeaponDefinition> all() {
        Map<WeaponId, WeaponDefinition> out = new EnumMap<>(WeaponId.class);
        for (WeaponId id : WeaponId.values()) {
            out.put(id, of(id));
        }
        return Collections.unmodifiableMap(out);
    }

    /**
     * Display name for any {@code weaponId} int on the wire: values below
     * {@link MeleeId#WIRE_ID_BASE} are gun ordinals, values at or above it are melee wire ids.
     */
    public static String displayNameForWireId(int wireId) {
        if (MeleeId.isMeleeWireId(wireId)) {
            return MeleeId.fromWireId(wireId).displayName();
        }
        return WeaponId.fromOrdinal(wireId).displayName();
    }

    private static final Map<WeaponId, WeaponDefinition> TABLE = buildTable();

    private static Map<WeaponId, WeaponDefinition> buildTable() {
        Map<WeaponId, WeaponDefinition> table = new EnumMap<>(WeaponId.class);

        put(table, WeaponId.IRON_SIDEARM, 27.6f, 6.3333f, 15, 75, 1.35f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(5.44f, 0.36f, 2.2f, 3.18f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.7f, 1.64f, 93f, 60f, 3.6f));

        put(table, WeaponId.VESPER_9, 29.9f, 5.3333f, 8, 40, 1.5f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(4.48f, 0.36f, 2.2f, 3.13f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.71f, 1.63f, 89f, 58f, 3.5f));

        put(table, WeaponId.NEST_HAWK, 23f, 15f, 20, 100, 1.55f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(7.68f, 0.36f, 2.2f, 3.5f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.65f, 1.71f, 124f, 81f, 4.3f));

        put(table, WeaponId.COBALT_COMPACT, 20.7f, 7f, 7, 35, 1.2f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(6.4f, 0.36f, 2.2f, 3.02f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.73f, 1.6f, 80f, 52f, 3.2f));

        put(table, WeaponId.ASHEN_SERVICE, 28.7f, 6f, 17, 85, 1.4f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(5.12f, 0.36f, 2.2f, 3.15f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.71f, 1.63f, 91f, 59f, 3.5f));

        put(table, WeaponId.REDLINE_45, 39.1f, 4.3333f, 10, 50, 1.65f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(6.08f, 0.36f, 2.2f, 3.61f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.63f, 1.74f, 135f, 88f, 4.6f));

        put(table, WeaponId.GLASS_NEEDLER, 25.3f, 4.6667f, 10, 50, 1.7f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(3.2f, 0.36f, 2.2f, 2.91f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.58f, 71f, 46f, 3f));

        put(table, WeaponId.HARBOR_19, 26.4f, 6.6667f, 15, 75, 1.3f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(5.44f, 0.36f, 2.2f, 3.1f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.71f, 1.62f, 86f, 56f, 3.4f));

        put(table, WeaponId.NIGHT_CLERK, 24.1f, 5.6667f, 12, 60, 1.55f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(4.8f, 0.36f, 2.2f, 2.99f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.73f, 1.6f, 77f, 50f, 3.2f));

        put(table, WeaponId.RUST_MARSHAL, 36.8f, 4f, 7, 35, 1.75f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(5.76f, 0.36f, 2.2f, 3.45f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.66f, 1.7f, 118f, 77f, 4.2f));

        put(table, WeaponId.TWIN_PEAK, 34.5f, 5f, 12, 60, 1.48f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(5.12f, 0.36f, 2.2f, 3.4f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.67f, 1.69f, 113f, 73f, 4.1f));

        put(table, WeaponId.QUIET_LEDGER, 16.1f, 6f, 10, 50, 1.45f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(2.88f, 0.36f, 2.2f, 2.59f, 3.6f, 5f),
            new WeaponDefinition.RecoilProfile(0.78f, 1.51f, 49f, 32f, 2.3f));

        put(table, WeaponId.BRASS_JUDGE, 23.4f, 1.5f, 5, 25, 3.1f, FireMode.SEMI, 4,
            new WeaponDefinition.SpreadProfile(13.44f, 0.38f, 2.3f, 4.04f, 3.7f, 4.5f),
            new WeaponDefinition.RecoilProfile(0.57f, 1.83f, 183f, 119f, 5.5f));

        put(table, WeaponId.EMBER_WHEEL, 78.2f, 1.3333f, 6, 30, 2.8f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(6.4f, 0.38f, 2.3f, 4.31f, 3.7f, 4.5f),
            new WeaponDefinition.RecoilProfile(0.53f, 1.89f, 216f, 140f, 6.1f));

        put(table, WeaponId.DUST_CYLINDER, 59.8f, 1.1667f, 6, 30, 3f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(7.04f, 0.38f, 2.3f, 3.99f, 3.7f, 4.5f),
            new WeaponDefinition.RecoilProfile(0.58f, 1.82f, 176f, 114f, 5.4f));

        put(table, WeaponId.LONGSPUR_44, 82.8f, 1.25f, 6, 30, 2.9f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(5.12f, 0.38f, 2.3f, 4.37f, 3.7f, 4.5f),
            new WeaponDefinition.RecoilProfile(0.52f, 1.9f, 222f, 144f, 6.2f));

        put(table, WeaponId.GRAVE_ORBIT, 55.2f, 2.3333f, 6, 30, 2.4f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(7.68f, 0.38f, 2.3f, 3.77f, 3.7f, 4.5f),
            new WeaponDefinition.RecoilProfile(0.61f, 1.77f, 152f, 99f, 4.9f));

        put(table, WeaponId.COPPER_LAW, 48.3f, 2f, 6, 30, 2.5f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(5.76f, 0.38f, 2.3f, 3.59f, 3.7f, 4.5f),
            new WeaponDefinition.RecoilProfile(0.64f, 1.73f, 132f, 86f, 4.5f));

        put(table, WeaponId.BREAKDAWN, 63.2f, 1.6667f, 7, 35, 2.2f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(5.44f, 0.38f, 2.3f, 3.88f, 3.7f, 4.5f),
            new WeaponDefinition.RecoilProfile(0.59f, 1.8f, 164f, 107f, 5.2f));

        put(table, WeaponId.IRON_SIX, 73.6f, 1.4167f, 6, 30, 2.7f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(6.08f, 0.38f, 2.3f, 4.21f, 3.7f, 4.5f),
            new WeaponDefinition.RecoilProfile(0.54f, 1.87f, 202f, 131f, 5.9f));

        put(table, WeaponId.WASP_NEST, 23f, 13.3333f, 30, 150, 1.7f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(6.4f, 0.42f, 1.85f, 2.86f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.75f, 1.57f, 67f, 44f, 2.9f));

        put(table, WeaponId.RATTLE_CAGE, 25.3f, 10f, 32, 160, 1.85f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(7.04f, 0.42f, 1.85f, 2.96f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.59f, 75f, 49f, 3.1f));

        put(table, WeaponId.SMOKE_STITCH, 20.7f, 15f, 50, 250, 2.1f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.12f, 0.4f, 1.8f, 2.69f, 2.8f, 9f),
            new WeaponDefinition.RecoilProfile(0.78f, 1.53f, 56f, 36f, 2.5f));

        put(table, WeaponId.METRO_SPRAY, 27.6f, 18.3333f, 30, 150, 1.6f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(10.24f, 0.42f, 1.85f, 3.29f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.69f, 1.66f, 103f, 67f, 3.8f));

        put(table, WeaponId.VELVET_BUZZ, 26.4f, 17.5f, 25, 125, 1.75f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.76f, 0.42f, 1.85f, 2.75f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.77f, 1.54f, 59f, 38f, 2.6f));

        put(table, WeaponId.GRID_HORNET, 19.5f, 15.8333f, 20, 100, 1.55f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(4.48f, 0.4f, 1.8f, 2.64f, 2.8f, 9f),
            new WeaponDefinition.RecoilProfile(0.78f, 1.52f, 52f, 34f, 2.4f));

        put(table, WeaponId.CINDER_SMG, 24.1f, 12.5f, 35, 175, 1.9f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(6.72f, 0.42f, 1.85f, 3.07f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.72f, 1.62f, 84f, 55f, 3.4f));

        put(table, WeaponId.POCKET_STORM, 21.8f, 14.1667f, 20, 100, 1.5f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(7.36f, 0.42f, 1.85f, 2.91f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.58f, 71f, 46f, 3f));

        put(table, WeaponId.WIRE_CHOIR, 23f, 9.1667f, 32, 160, 2f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(8.32f, 0.42f, 1.85f, 3.02f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.73f, 1.6f, 80f, 52f, 3.2f));

        put(table, WeaponId.ASH_HOPPER, 27.6f, 11.6667f, 50, 250, 2.4f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(8f, 0.42f, 1.85f, 3.13f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.71f, 1.63f, 89f, 58f, 3.5f));

        put(table, WeaponId.CLIP_DAISY, 26.4f, 7.5f, 30, 150, 2.1f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(7.68f, 0.42f, 1.85f, 2.99f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.73f, 1.6f, 77f, 50f, 3.2f));

        put(table, WeaponId.NEON_CHATTER, 20.7f, 20f, 40, 200, 1.65f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(8.96f, 0.42f, 1.85f, 2.8f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.76f, 1.56f, 63f, 41f, 2.8f));

        put(table, WeaponId.HARBOR_SWARM, 21.8f, 13f, 30, 150, 1.6f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(6.4f, 0.42f, 1.85f, 2.88f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.75f, 1.57f, 69f, 45f, 2.9f));

        put(table, WeaponId.SOFT_RATCHET, 19.5f, 12f, 25, 125, 1.8f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(4.8f, 0.42f, 1.85f, 2.64f, 2.8f, 9.5f),
            new WeaponDefinition.RecoilProfile(0.78f, 1.52f, 52f, 34f, 2.4f));

        put(table, WeaponId.COAT_NEEDLE, 18.4f, 14.6667f, 20, 100, 1.4f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(7.04f, 0.4f, 1.8f, 2.78f, 2.8f, 9f),
            new WeaponDefinition.RecoilProfile(0.77f, 1.55f, 61f, 40f, 2.7f));

        put(table, WeaponId.BRIEFCASE, 21.8f, 10.8333f, 32, 160, 1.9f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(7.68f, 0.4f, 1.8f, 2.91f, 2.8f, 9f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.58f, 71f, 46f, 3f));

        put(table, WeaponId.IRON_CARBINE, 32.2f, 12f, 30, 120, 2.1f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(3.84f, 0.3f, 2f, 3.04f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.72f, 1.61f, 82f, 53f, 3.3f));

        put(table, WeaponId.RIDGEBACK, 36.8f, 10f, 30, 120, 2.3f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.12f, 0.3f, 2f, 3.29f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.69f, 1.66f, 103f, 67f, 3.8f));

        put(table, WeaponId.PALE_LANCE, 31f, 11.6667f, 30, 120, 2.05f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(3.52f, 0.3f, 2f, 2.96f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.59f, 75f, 49f, 3.1f));

        put(table, WeaponId.SAND_VIPER, 33.3f, 11.3333f, 30, 120, 2f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(3.84f, 0.3f, 2f, 2.91f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.58f, 71f, 46f, 3f));

        put(table, WeaponId.BLACK_CORRIDOR, 29.9f, 13.3333f, 30, 120, 1.95f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(4.8f, 0.3f, 2f, 3.02f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.73f, 1.6f, 80f, 52f, 3.2f));

        put(table, WeaponId.OAKLINE_RIFLE, 34.5f, 7f, 20, 80, 2.2f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(2.88f, 0.3f, 2f, 2.86f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.75f, 1.57f, 67f, 44f, 2.9f));

        put(table, WeaponId.HALCYON_16, 32.2f, 3.3611f, 25, 100, 2.15f, FireMode.BURST, 1,
            new WeaponDefinition.SpreadProfile(4.16f, 0.3f, 2f, 2.99f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.73f, 1.6f, 77f, 50f, 3.2f));

        put(table, WeaponId.BRINE_CARBINE, 31f, 12.5f, 30, 120, 1.9f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(3.84f, 0.3f, 2f, 2.94f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.59f, 73f, 47f, 3.1f));

        put(table, WeaponId.SOLAR_SPINE, 32.2f, 10.8333f, 30, 120, 2.05f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(3.52f, 0.3f, 2f, 3.07f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.72f, 1.62f, 84f, 55f, 3.4f));

        put(table, WeaponId.FROST_RECEIVER, 33.3f, 10.3333f, 30, 120, 2.2f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(3.2f, 0.3f, 2f, 2.99f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.73f, 1.6f, 77f, 50f, 3.2f));

        put(table, WeaponId.EMBER_PATH, 29.9f, 13f, 30, 120, 2.1f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(4.16f, 0.3f, 2f, 2.91f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.58f, 71f, 46f, 3f));

        put(table, WeaponId.KESTREL_AR, 28.7f, 14.1667f, 30, 120, 1.85f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.12f, 0.3f, 2f, 3.02f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.73f, 1.6f, 80f, 52f, 3.2f));

        put(table, WeaponId.DUSK_FOLD, 35.6f, 10.6667f, 30, 120, 2.15f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.44f, 0.3f, 2f, 3.23f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.69f, 1.65f, 98f, 64f, 3.7f));

        put(table, WeaponId.COPPER_THREAD, 32.2f, 11.8333f, 30, 120, 2f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(3.84f, 0.3f, 2f, 2.96f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.74f, 1.59f, 75f, 49f, 3.1f));

        put(table, WeaponId.YARD_DOG, 31f, 12.6667f, 40, 160, 2.25f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.76f, 0.3f, 2f, 3.13f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.71f, 1.63f, 89f, 58f, 3.5f));

        put(table, WeaponId.QUIET_HOLLOW, 34.5f, 11.3333f, 30, 120, 2.05f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(4.16f, 0.3f, 2f, 2.88f, 3f, 7.5f),
            new WeaponDefinition.RecoilProfile(0.75f, 1.57f, 69f, 45f, 2.9f));

        put(table, WeaponId.VEST_STING, 20.7f, 15.3333f, 20, 100, 1.35f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(6.72f, 0.4f, 1.8f, 2.83f, 2.8f, 9f),
            new WeaponDefinition.RecoilProfile(0.76f, 1.56f, 65f, 42f, 2.8f));

        put(table, WeaponId.METRO_FOLD, 21.8f, 13.3333f, 25, 125, 1.5f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(6.4f, 0.4f, 1.8f, 2.86f, 2.8f, 9f),
            new WeaponDefinition.RecoilProfile(0.75f, 1.57f, 67f, 44f, 2.9f));

        put(table, WeaponId.LONG_MILE, 55.2f, 4.3333f, 20, 100, 2.4f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(1.92f, 0.22f, 2.4f, 3.5f, 3.4f, 5.5f),
            new WeaponDefinition.RecoilProfile(0.65f, 1.71f, 124f, 81f, 4.3f));

        put(table, WeaponId.GLASS_RIDGE, 50.6f, 5f, 20, 100, 2.3f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(1.6f, 0.22f, 2.4f, 3.34f, 3.4f, 5.5f),
            new WeaponDefinition.RecoilProfile(0.68f, 1.68f, 108f, 70f, 4f));

        put(table, WeaponId.THORN_DMR, 57.5f, 3.6667f, 10, 50, 2.55f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(1.6f, 0.22f, 2.4f, 3.67f, 3.4f, 5.5f),
            new WeaponDefinition.RecoilProfile(0.63f, 1.75f, 140f, 91f, 4.7f));

        put(table, WeaponId.HARBOR_MARKSMAN, 52.9f, 4.6667f, 20, 100, 2.35f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(2.24f, 0.22f, 2.4f, 3.45f, 3.4f, 5.5f),
            new WeaponDefinition.RecoilProfile(0.66f, 1.7f, 118f, 77f, 4.2f));

        put(table, WeaponId.IRON_LEDGER, 48.3f, 10.8333f, 20, 80, 2.5f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(4.48f, 0.26f, 2.2f, 3.72f, 3.2f, 6f),
            new WeaponDefinition.RecoilProfile(0.62f, 1.76f, 146f, 95f, 4.8f));

        put(table, WeaponId.PALE_WITNESS, 51.7f, 4f, 10, 50, 2.6f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(1.28f, 0.22f, 2.4f, 3.4f, 3.4f, 5.5f),
            new WeaponDefinition.RecoilProfile(0.67f, 1.69f, 113f, 73f, 4.1f));

        put(table, WeaponId.RANGE_CLERK, 41.4f, 6f, 20, 100, 2.15f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(2.24f, 0.22f, 2.4f, 3.18f, 3.4f, 5.5f),
            new WeaponDefinition.RecoilProfile(0.7f, 1.64f, 93f, 60f, 3.6f));

        put(table, WeaponId.ASH_PIN, 59.8f, 3.3333f, 10, 50, 2.7f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(1.6f, 0.22f, 2.4f, 3.77f, 3.4f, 5.5f),
            new WeaponDefinition.RecoilProfile(0.61f, 1.77f, 152f, 99f, 4.9f));

        put(table, WeaponId.COPPER_SPAN, 46f, 2.1389f, 20, 80, 2.45f, FireMode.BURST, 1,
            new WeaponDefinition.SpreadProfile(3.84f, 0.26f, 2.2f, 3.59f, 3.2f, 6f),
            new WeaponDefinition.RecoilProfile(0.64f, 1.73f, 132f, 86f, 4.5f));

        put(table, WeaponId.HIGH_BENCH, 62.1f, 3f, 10, 50, 2.8f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(1.28f, 0.22f, 2.4f, 3.67f, 3.4f, 5.5f),
            new WeaponDefinition.RecoilProfile(0.63f, 1.75f, 140f, 91f, 4.7f));

        put(table, WeaponId.NIGHT_GLASS, 101.2f, 0.8f, 5, 25, 3f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.64f, 0.18f, 2.7f, 4.21f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.54f, 1.87f, 202f, 131f, 5.9f));

        put(table, WeaponId.WINTER_BOLT, 105.8f, 0.6667f, 5, 25, 3.2f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.64f, 0.18f, 2.7f, 4.26f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.53f, 1.88f, 209f, 136f, 6f));

        put(table, WeaponId.CATHEDRAL, 126.5f, 0.5333f, 5, 25, 3.5f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.48f, 0.18f, 2.7f, 4.53f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.49f, 1.94f, 243f, 158f, 6.6f));

        put(table, WeaponId.LONG_SILENCE, 92f, 0.7f, 10, 50, 3.1f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.8f, 0.18f, 2.7f, 3.99f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.58f, 1.82f, 176f, 114f, 5.4f));

        put(table, WeaponId.MAGPIE, 149.5f, 0.4667f, 5, 25, 3.8f, FireMode.SEMI, 1,
            new WeaponDefinition.SpreadProfile(0.64f, 0.18f, 2.7f, 4.75f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.46f, 1.99f, 273f, 177f, 7.1f));

        put(table, WeaponId.ICE_SPINE, 120.7f, 0.6f, 5, 25, 3.4f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.48f, 0.18f, 2.7f, 4.48f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.5f, 1.93f, 236f, 153f, 6.5f));

        put(table, WeaponId.DISTANT_CLERK, 89.7f, 0.9167f, 10, 50, 2.7f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.96f, 0.18f, 2.7f, 4.04f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.57f, 1.83f, 183f, 119f, 5.5f));

        put(table, WeaponId.BLACK_HORIZON, 110.4f, 0.6333f, 5, 25, 3.3f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.58f, 0.18f, 2.7f, 4.39f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.51f, 1.91f, 226f, 147f, 6.3f));

        put(table, WeaponId.EMBER_GLASS, 115f, 0.5667f, 5, 25, 3.35f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.64f, 0.18f, 2.7f, 4.42f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.51f, 1.92f, 229f, 149f, 6.4f));

        put(table, WeaponId.TIDE_NEEDLE, 96.6f, 0.7333f, 5, 25, 3.05f, FireMode.BOLT, 1,
            new WeaponDefinition.SpreadProfile(0.7f, 0.18f, 2.7f, 4.15f, 4f, 4f),
            new WeaponDefinition.RecoilProfile(0.55f, 1.86f, 196f, 127f, 5.8f));

        put(table, WeaponId.DOOR_HYMN, 20.8f, 1.1667f, 6, 48, 3.2f, FireMode.PUMP, 8,
            new WeaponDefinition.SpreadProfile(13.44f, 0.52f, 1.9f, 4.21f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.54f, 1.87f, 202f, 131f, 5.9f));

        put(table, WeaponId.ROOM_SWEEPER, 18.2f, 3.6667f, 10, 80, 2.6f, FireMode.AUTO, 8,
            new WeaponDefinition.SpreadProfile(15.36f, 0.52f, 1.9f, 4.04f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.57f, 1.83f, 183f, 119f, 5.5f));

        put(table, WeaponId.IRON_GOOSE, 19.5f, 2.6667f, 5, 40, 2.8f, FireMode.SEMI, 8,
            new WeaponDefinition.SpreadProfile(10.24f, 0.52f, 1.9f, 3.99f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.58f, 1.82f, 176f, 114f, 5.4f));

        put(table, WeaponId.SCATTER_BENCH, 20.8f, 1.25f, 8, 64, 3.4f, FireMode.PUMP, 8,
            new WeaponDefinition.SpreadProfile(12.8f, 0.52f, 1.9f, 4.1f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.56f, 1.84f, 189f, 123f, 5.6f));

        put(table, WeaponId.PUMP_CHAPEL, 22.1f, 1.3333f, 5, 40, 2.9f, FireMode.PUMP, 8,
            new WeaponDefinition.SpreadProfile(16f, 0.52f, 1.9f, 4.31f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.53f, 1.89f, 216f, 140f, 6.1f));

        put(table, WeaponId.MAGPIE_12, 19.5f, 1.5f, 2, 16, 2f, FireMode.BREAK, 8,
            new WeaponDefinition.SpreadProfile(9.6f, 0.52f, 1.9f, 3.94f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.58f, 1.81f, 170f, 110f, 5.3f));

        put(table, WeaponId.HARBOR_GATE, 20.8f, 3f, 8, 64, 2.5f, FireMode.SEMI, 8,
            new WeaponDefinition.SpreadProfile(12.16f, 0.52f, 1.9f, 4.07f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.56f, 1.84f, 186f, 121f, 5.6f));

        put(table, WeaponId.CINDER_TUBE, 23.4f, 1.6667f, 2, 16, 1.9f, FireMode.BREAK, 8,
            new WeaponDefinition.SpreadProfile(16.64f, 0.52f, 1.9f, 4.53f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.49f, 1.94f, 243f, 158f, 6.6f));

        put(table, WeaponId.SHORT_GOSPEL, 23.4f, 1.4167f, 4, 32, 2.6f, FireMode.PUMP, 8,
            new WeaponDefinition.SpreadProfile(18.56f, 0.52f, 1.9f, 4.58f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.48f, 1.95f, 251f, 163f, 6.7f));

        put(table, WeaponId.TWIN_BARREL, 20.8f, 1.5833f, 2, 16, 1.85f, FireMode.BREAK, 8,
            new WeaponDefinition.SpreadProfile(11.52f, 0.52f, 1.9f, 4.15f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.55f, 1.86f, 196f, 127f, 5.8f));

        put(table, WeaponId.ASH_HOPPER_12, 16.9f, 4f, 12, 96, 2.8f, FireMode.AUTO, 8,
            new WeaponDefinition.SpreadProfile(14.72f, 0.52f, 1.9f, 3.99f, 2.7f, 6f),
            new WeaponDefinition.RecoilProfile(0.58f, 1.82f, 176f, 114f, 5.4f));

        put(table, WeaponId.MILLSTONE, 29.9f, 14.1667f, 100, 200, 6.4f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.12f, 0.34f, 2.1f, 3.07f, 3f, 6.5f),
            new WeaponDefinition.RecoilProfile(0.72f, 1.62f, 84f, 55f, 3.4f));

        put(table, WeaponId.BELT_HYMN, 34.5f, 10.8333f, 100, 200, 7f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.76f, 0.34f, 2.1f, 3.34f, 3f, 6.5f),
            new WeaponDefinition.RecoilProfile(0.68f, 1.68f, 108f, 70f, 4f));

        put(table, WeaponId.IRON_RAIN, 33.3f, 9.1667f, 100, 200, 6.8f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(5.44f, 0.34f, 2.1f, 3.29f, 3f, 6.5f),
            new WeaponDefinition.RecoilProfile(0.69f, 1.66f, 103f, 67f, 3.8f));

        put(table, WeaponId.YARD_SAW, 32.2f, 10f, 75, 150, 5.5f, FireMode.AUTO, 1,
            new WeaponDefinition.SpreadProfile(6.08f, 0.34f, 2.1f, 3.23f, 3f, 6.5f),
            new WeaponDefinition.RecoilProfile(0.69f, 1.65f, 98f, 64f, 3.7f));

        return Collections.unmodifiableMap(table);
    }

    private static void put(
            Map<WeaponId, WeaponDefinition> table,
            WeaponId id,
            float damage,
            float fireRateHz,
            int magazineSize,
            int reserveAmmo,
            float reloadSeconds,
            FireMode fireMode,
            int pelletCount,
            WeaponDefinition.SpreadProfile spread,
            WeaponDefinition.RecoilProfile recoil) {
        table.put(id, new WeaponDefinition(
            id,
            damage,
            fireRateHz,
            magazineSize,
            reserveAmmo,
            reloadSeconds,
            fireMode,
            pelletCount,
            spread,
            recoil,
            WeaponBallistics.of(id)));
    }
}
